### ISSUE TITLE
New version of Showtimes

### ISSUE THREAD

**Issue by erunion** [ferdx/ferd-flix#2]
Hey there! Looks like you're the only project on NPM that's dependent upon my Showtimes library.

I'd just like to let you know that I pushed out v2.0.0 of it tonight, which includes some cool new features (`.getMovies()`, a complete rebuild in ES6), but it is unfortunately backwards compatible.

Looking at your guys' usage of it, it should be a 1 line change to upgrade by just changing:

```
var location = showtimes(locator, { lang: 'en', pageLimit: 10 });
```

to

```
var location = new showtimes(locator, { lang: 'en', pageLimit: 10 });
```

I've written some documentation on upgrading, [here](https://github.com/erunion/showtimes#upgrading-to-v2), if you're curious.

Thanks for using my library!

**Comment by callmenick** [comment]
Awesome @erunion thanks for the insight! Great library by the way :)
